version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c 'yarn && yarn dev'
    volumes:
      - .:/app
    ports:
      - 5173:5173
    environment: 
      - NODE_ENV=development
    tty: true
