version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=development
    tty: true
